name: Benchmarks

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: Run benchmarks
        run: cargo bench --bench performance -- --output-format bencher | tee benchmarks.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Rust Benchmark
          tool: "cargo"
          output-file-path: benchmarks.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: "110%"
          comment-on-alert: true
          fail-on-alert: true
          gh-pages-branch: "benchmarks"
          benchmark-data-dir-path: "benchmarks"
